export interface ThemeConfig {
  canvasBackground: string;
  nodeDefaultColor: string;
  labelColor: string;
  uiPanelBackground: string;
  uiButtonBackground: string;
  uiButtonTextColor: string;
  uiInputBackground: string;
  uiInputTextColor: string;
  uiInputBorder: string;
}

export const THEMES: Record<string, ThemeConfig> = {
  "atom-light": {
    canvasBackground: "#fafafa",
    nodeDefaultColor: "#383a42",
    labelColor: "#383a42",
    uiPanelBackground: "#ededed",
    uiButtonBackground: "#dad8d8",
    uiButtonTextColor: "#383a42",
    uiInputBackground: "#ededed",
    uiInputTextColor: "#383a42",
    uiInputBorder: "#aeadb3",
  },
  "amoled-dark": {
    canvasBackground: "#0a0a0a",
    nodeDefaultColor: "#ffffff",
    labelColor: "#ffffff",
    uiPanelBackground: "#1e1e1e",
    uiButtonBackground: "#323232",
    uiButtonTextColor: "#ffffff",
    uiInputBackground: "#1e1e1e",
    uiInputTextColor: "#ffffff",
    uiInputBorder: "#7e7e7e",
  },
  "atom-dark": {
    canvasBackground: "#272b34",
    nodeDefaultColor: "#dddedf",
    labelColor: "#dddedf",
    uiPanelBackground: "#303540",
    uiButtonBackground: "#393f4c",
    uiButtonTextColor: "#dddedf",
    uiInputBackground: "#303540",
    uiInputTextColor: "#dddedf",
    uiInputBorder: "#505562",
  },
  "biscuit-dark": {
    canvasBackground: "#453636",
    nodeDefaultColor: "#ffe9c7",
    labelColor: "#ffe9c7",
    uiPanelBackground: "#534141",
    uiButtonBackground: "#644f4f",
    uiButtonTextColor: "#ffe9c7",
    uiInputBackground: "#534141",
    uiInputTextColor: "#ffe9c7",
    uiInputBorder: "#8c6e6e",
  },
  "coffee-dark": {
    canvasBackground: "#3a3845",
    nodeDefaultColor: "#fadac3",
    labelColor: "#fadac3",
    uiPanelBackground: "#4c464e",
    uiButtonBackground: "#554d52",
    uiButtonTextColor: "#fadac3",
    uiInputBackground: "#4c464e",
    uiInputTextColor: "#fadac3",
    uiInputBorder: "#786660",
  },
  "dracula": {
    canvasBackground: "#282a36",
    nodeDefaultColor: "#f8f8f2",
    labelColor: "#f8f8f2",
    uiPanelBackground: "#303241",
    uiButtonBackground: "#383b4c",
    uiButtonTextColor: "#f8f8f2",
    uiInputBackground: "#303241",
    uiInputTextColor: "#f8f8f2",
    uiInputBorder: "#585c74",
  },
  "everforest-light": {
    canvasBackground: "#fdf6e3",
    nodeDefaultColor: "#5c6a72",
    labelColor: "#5c6a72",
    uiPanelBackground: "#f3efda",
    uiButtonBackground: "#edead5",
    uiButtonTextColor: "#5c6a72",
    uiInputBackground: "#f3efda",
    uiInputTextColor: "#5c6a72",
    uiInputBorder: "#dfdbc8",
  },
  "everforest-dark": {
    canvasBackground: "#2f383e",
    nodeDefaultColor: "#d3c6aa",
    labelColor: "#d3c6aa",
    uiPanelBackground: "#374247",
    uiButtonBackground: "#404c51",
    uiButtonTextColor: "#d3c6aa",
    uiInputBackground: "#374247",
    uiInputTextColor: "#d3c6aa",
    uiInputBorder: "#515b61",
  },
  "flexoki-dark": {
    canvasBackground: "#1c1b1a",
    nodeDefaultColor: "#cfcec4",
    labelColor: "#cfcec4",
    uiPanelBackground: "#343331",
    uiButtonBackground: "#403e3c",
    uiButtonTextColor: "#cfcec4",
    uiInputBackground: "#343331",
    uiInputTextColor: "#cfcec4",
    uiInputBorder: "#6f6e69",
  },
  "generic-dark": {
    canvasBackground: "#2a2a2a",
    nodeDefaultColor: "#ffffff",
    labelColor: "#ffffff",
    uiPanelBackground: "#3f3f3f",
    uiButtonBackground: "#545454",
    uiButtonTextColor: "#ffffff",
    uiInputBackground: "#3f3f3f",
    uiInputTextColor: "#ffffff",
    uiInputBorder: "#7e7e7e",
  },
  "gruvbox-dark": {
    canvasBackground: "#282828",
    nodeDefaultColor: "#fbf1c7",
    labelColor: "#fbf1c7",
    uiPanelBackground: "#32302f",
    uiButtonBackground: "#3c3836",
    uiButtonTextColor: "#fbf1c7",
    uiInputBackground: "#32302f",
    uiInputTextColor: "#fbf1c7",
    uiInputBorder: "#665c54",
  },
  "gruvbox-light": {
    canvasBackground: "#f9f5d7",
    nodeDefaultColor: "#282828",
    labelColor: "#282828",
    uiPanelBackground: "#f2e5bc",
    uiButtonBackground: "#ebdbb3",
    uiButtonTextColor: "#282828",
    uiInputBackground: "#f2e5bc",
    uiInputTextColor: "#282828",
    uiInputBorder: "#bdae93",
  },
  "kanagawa-dark": {
    canvasBackground: "#1f1f28",
    nodeDefaultColor: "#dcd7ba",
    labelColor: "#dcd7ba",
    uiPanelBackground: "#2a2a37",
    uiButtonBackground: "#363645",
    uiButtonTextColor: "#dcd7ba",
    uiInputBackground: "#2a2a37",
    uiInputTextColor: "#dcd7ba",
    uiInputBorder: "#49495f",
  },
  "luminescence-light": {
    canvasBackground: "#f2eee8",
    nodeDefaultColor: "#654941",
    labelColor: "#654941",
    uiPanelBackground: "#cdb7b1",
    uiButtonBackground: "#e1d4d0",
    uiButtonTextColor: "#654941",
    uiInputBackground: "#cdb7b1",
    uiInputTextColor: "#654941",
    uiInputBorder: "#dfdbc8",
  },
  "material-mint-light": {
    canvasBackground: "#bdd6db",
    nodeDefaultColor: "#05090a",
    labelColor: "#05090a",
    uiPanelBackground: "#6da5b0",
    uiButtonBackground: "#56939f",
    uiButtonTextColor: "#05090a",
    uiInputBackground: "#6da5b0",
    uiInputTextColor: "#05090a",
    uiInputBorder: "#39626a",
  },
  "material-mint-dark": {
    canvasBackground: "#121f21",
    nodeDefaultColor: "#bdd6db",
    labelColor: "#bdd6db",
    uiPanelBackground: "#1d3135",
    uiButtonBackground: "#2b4950",
    uiButtonTextColor: "#bdd6db",
    uiInputBackground: "#1d3135",
    uiInputTextColor: "#bdd6db",
    uiInputBorder: "#477a85",
  },
  "nord-dark": {
    canvasBackground: "#434c5e",
    nodeDefaultColor: "#eceff4",
    labelColor: "#eceff4",
    uiPanelBackground: "#4d576a",
    uiButtonBackground: "#67748e",
    uiButtonTextColor: "#eceff4",
    uiInputBackground: "#4d576a",
    uiInputTextColor: "#eceff4",
    uiInputBorder: "#959eb2",
  },
  "nord-darker": {
    canvasBackground: "#2e3440",
    nodeDefaultColor: "#eceff4",
    labelColor: "#eceff4",
    uiPanelBackground: "#3b4252",
    uiButtonBackground: "#434c5e",
    uiButtonTextColor: "#eceff4",
    uiInputBackground: "#3b4252",
    uiInputTextColor: "#eceff4",
    uiInputBorder: "#959eb2",
  },
  "nord-light": {
    canvasBackground: "#eceff4",
    nodeDefaultColor: "#2e3440",
    labelColor: "#2e3440",
    uiPanelBackground: "#e5e9f0",
    uiButtonBackground: "#d8dee9",
    uiButtonTextColor: "#2e3440",
    uiInputBackground: "#e5e9f0",
    uiInputTextColor: "#2e3440",
    uiInputBorder: "#8fbcbb",
  },
  "notion-light": {
    canvasBackground: "#ffffff",
    nodeDefaultColor: "#37352f",
    labelColor: "#37352f",
    uiPanelBackground: "#d0d4d7",
    uiButtonBackground: "#bdc3c7",
    uiButtonTextColor: "#37352f",
    uiInputBackground: "#d0d4d7",
    uiInputTextColor: "#37352f",
    uiInputBorder: "#919ba1",
  },
  "notion-dark": {
    canvasBackground: "#3d4448",
    nodeDefaultColor: "#e3e6e8",
    labelColor: "#e3e6e8",
    uiPanelBackground: "#4b5358",
    uiButtonBackground: "#5e686e",
    uiButtonTextColor: "#e3e6e8",
    uiInputBackground: "#4b5358",
    uiInputTextColor: "#e3e6e8",
    uiInputBorder: "#869198",
  },
  "rosebox": {
    canvasBackground: "#232323",
    nodeDefaultColor: "#a3a5aa",
    labelColor: "#a3a5aa",
    uiPanelBackground: "#282828",
    uiButtonBackground: "#333333",
    uiButtonTextColor: "#a3a5aa",
    uiInputBackground: "#282828",
    uiInputTextColor: "#a3a5aa",
    uiInputBorder: "#474747",
  },
  "rosepine-dark": {
    canvasBackground: "#191724",
    nodeDefaultColor: "#e0def4",
    labelColor: "#e0def4",
    uiPanelBackground: "#1f1d2e",
    uiButtonBackground: "#21202e",
    uiButtonTextColor: "#e0def4",
    uiInputBackground: "#1f1d2e",
    uiInputTextColor: "#e0def4",
    uiInputBorder: "#363253",
  },
  "royal-velvet": {
    canvasBackground: "#1e1e24",
    nodeDefaultColor: "#f8f8f2",
    labelColor: "#f8f8f2",
    uiPanelBackground: "#303241",
    uiButtonBackground: "#383b4c",
    uiButtonTextColor: "#f8f8f2",
    uiInputBackground: "#303241",
    uiInputTextColor: "#f8f8f2",
    uiInputBorder: "#585c74",
  },
  "sandy-beaches-light": {
    canvasBackground: "#f0eae2",
    nodeDefaultColor: "#685850",
    labelColor: "#685850",
    uiPanelBackground: "#ded8d1",
    uiButtonBackground: "#d4cdc8",
    uiButtonTextColor: "#685850",
    uiInputBackground: "#ded8d1",
    uiInputTextColor: "#685850",
    uiInputBorder: "#82756e",
  },
  "solarized-dark": {
    canvasBackground: "#073642",
    nodeDefaultColor: "#fdf6e3",
    labelColor: "#fdf6e3",
    uiPanelBackground: "#0a4c5c",
    uiButtonBackground: "#266173",
    uiButtonTextColor: "#fdf6e3",
    uiInputBackground: "#0a4c5c",
    uiInputTextColor: "#fdf6e3",
    uiInputBorder: "#6aa8af",
  },
  "solarized-light": {
    canvasBackground: "#fdf6e3",
    nodeDefaultColor: "#002b36",
    labelColor: "#002b36",
    uiPanelBackground: "#adb8b8",
    uiButtonBackground: "#91a0a1",
    uiButtonTextColor: "#002b36",
    uiInputBackground: "#adb8b8",
    uiInputTextColor: "#002b36",
    uiInputBorder: "#657b83",
  },
  "thorns": {
    canvasBackground: "#151515",
    nodeDefaultColor: "#d8d0d5",
    labelColor: "#d8d0d5",
    uiPanelBackground: "#2e2e2e",
    uiButtonBackground: "#3b3b3b",
    uiButtonTextColor: "#d8d0d5",
    uiInputBackground: "#2e2e2e",
    uiInputTextColor: "#d8d0d5",
    uiInputBorder: "#505050",
  },
};

export const THEME_LABELS: Record<string, string> = {
  "amoled-dark": "AMOLED 暗色",
  "atom-dark": "Atom 暗色",
  "atom-light": "Atom 亮色",
  "biscuit-dark": "Biscuit 暗色",
  "coffee-dark": "Coffee 暗色",
  "dracula": "Dracula",
  "everforest-dark": "Everforest 暗色",
  "everforest-light": "Everforest 亮色",
  "flexoki-dark": "Flexoki 暗色",
  "generic-dark": "通用暗色",
  "gruvbox-dark": "Gruvbox 暗色",
  "gruvbox-light": "Gruvbox 亮色",
  "kanagawa-dark": "Kanagawa 暗色",
  "luminescence-light": "Luminescence 亮色",
  "material-mint-dark": "Material Mint 暗色",
  "material-mint-light": "Material Mint 亮色",
  "nord-dark": "Nord 暗色",
  "nord-darker": "Nord 深暗",
  "nord-light": "Nord 亮色",
  "notion-dark": "Notion 暗色",
  "notion-light": "Notion 亮色",
  "rosebox": "Rosebox",
  "rosepine-dark": "Rosé Pine 暗色",
  "royal-velvet": "Royal Velvet",
  "sandy-beaches-light": "Sandy Beaches 亮色",
  "solarized-dark": "Solarized 暗色",
  "solarized-light": "Solarized 亮色",
  "thorns": "Thorns",
};

export function getTheme(name: string): ThemeConfig {
  return THEMES[name] || THEMES["generic-dark"];
}

export function getThemeLabel(name: string): string {
  return THEME_LABELS[name] || name;
}
